export * from './students';
export * from './admins';
export * from './teachers';
export * from './assignments';
export * from './enrollments';
export * from './courses';
export * from './attendances';
export * from './exams';
export * from './grades';
