import { ThemeProvider } from '@/providers/theme-provider';
import TRPCReactProvider from '@/trpc/react';
import { GeistSans } from 'geist/font/sans';
import type { Metadata } from 'next';

import '@/styles/globals.css';
import { Toaster } from '@/lib/components/ui/toaster';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type Props = { children: React.ReactNode };

export default function RootLayout({ children }: Props) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${GeistSans.variable} antialiased`}>
        <TRPCReactProvider>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
            <Toaster />
            {children}
          </ThemeProvider>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
